In [58]:
import pandas as pd
import numpy as np
from sklearn.impute import KNNImputer

In [59]:
delirium_mimic_dataset=pd.read_csv('merged_df_mvcv_charts_adm_diag_delirium_labels.csv')

In [60]:
delirium_mimic_dataset.head()

,Unnamed: 0,SUBJECT_ID,HADM_ID,ICUSTAY_ID,ABI Ankle BP L,ABI Brachial BP L,ALT,APACHE II,APS,ART BP Systolic,...,ADMISSION_LOCATION,DISCHARGE_LOCATION,INSURANCE,LANGUAGE,RELIGION,MARITAL_STATUS,ETHNICITY,GENDER,AGE,Delirium
0,0,23,124321.0,234044.0,NaN,NaN,NaN,NaN,NaN,122.180000,...,TRANSFER FROM HOSP/EXTRAM,HOME HEALTH CARE,Medicare,ENGL,CATHOLIC,MARRIED,WHITE,M,75.304110,0
1,10,34,144319.0,290505.0,NaN,NaN,NaN,NaN,NaN,128.055556,...,CLINIC REFERRAL/PREMATURE,HOME HEALTH CARE,Medicare,ENGL,CATHOLIC,MARRIED,WHITE,M,304.805479,0
2,18,36,165660.0,241249.0,NaN,NaN,12.0,NaN,NaN,127.950000,...,PHYS REFERRAL/NORMAL DELI,LONG TERM CARE HOSPITAL,Medicare,ENGL,NOT SPECIFIED,MARRIED,WHITE,M,72.775342,0
3,30,85,112077.0,291697.0,NaN,NaN,23.0,NaN,NaN,111.125000,...,CLINIC REFERRAL/PREMATURE,SNF,Medicare,ENGL,CATHOLIC,MARRIED,WHITE,M,76.898630,0
4,49,107,174162.0,264253.0,NaN,NaN,22.0,NaN,NaN,104.520000,...,CLINIC REFERRAL/PREMATURE,HOME,Medicare,ENGL,CATHOLIC,SEPARATED,HISPANIC OR LATINO,M,70.158904,0

In [61]:
delirium_mimic_dataset.columns

Index(['Unnamed: 0', 'SUBJECT_ID', 'HADM_ID', 'ICUSTAY_ID', 'ABI Ankle BP L',
       'ABI Brachial BP L', 'ALT', 'APACHE II', 'APS', 'ART BP Systolic',
       'ART BP mean', 'ART Lumen Volume', 'AST', 'Admission Weight (Kg)',
       'Albumin', 'AlbuminScore_ApacheIV', 'Albumin_ApacheIV',
       'Alkaline Phosphate', 'Ammonia', 'Anion gap',
       'Aortic Pressure Signal - Diastolic',
       'Aortic Pressure Signal - Systolic', 'Arterial Base Excess',
       'Arterial Blood Pressure mean', 'Arterial CO2 Pressure',
       'Arterial O2 Saturation', 'Assisted Systole', 'Augmented Diastole',
       'BUN', 'Brain Natiuretic Peptide (BNP)', 'BunScore_ApacheIV',
       'C Reactive Protein (CRP)', 'CFI (PiCCO)', 'CI (PiCCO)', 'CK (CPK)',
       'CK-MB', 'CO (Arterial)', 'CO (PiCCO)', 'CO2 production',
       'Calcium non-ionized', 'Dialysate Rate', 'Differential-Atyps',
       'Differential-Bands', 'Differential-Basos', 'Differential-Eos',
       'Differential-Lymphs', 'Differential-Monos', 'Differential-Neuts',
       'Fibrinogen', 'Filter Pressure', 'Gentamicin (Random)', 'HCO3 (serum)',
       'Heart Rate', 'Impaired Skin Depth #1', 'Impaired Skin Length #1',
       'Impaired Skin Width #1', 'Inspired O2 Fraction',
       'Intra Cranial Pressure', 'Ionized Calcium', 'LDH', 'LDL measured',
       'LOS pre-ICU admission', 'Lactic Acid', 'Lipase', 'MDI #1 Puff',
       'Magnesium', 'Non Invasive Blood Pressure mean',
       'Non-Invasive Blood Pressure mean', 'O2 saturation pulseoxymetry',
       'Potassium (whole blood)', 'Pulmonary Artery Pressure mean',
       'Respiratory Rate', 'Skeletal Traction #1 - Pounds', 'Sodium (serum)',
       'Temperature Celsius', 'Total Bilirubin', 'Venous CO2 Pressure',
       'Venous O2 Pressure', 'Ventilator Tank #1', 'WBC', 'Chest Tubes Other',
       'Fentanyl', 'Free Water', 'Insulin', 'KCL', 'Kphos', 'Protonix',
       'Sodium Phosphate', 'LOS', 'ADMISSION_TYPE', 'ADMISSION_LOCATION',
       'DISCHARGE_LOCATION', 'INSURANCE', 'LANGUAGE', 'RELIGION',
       'MARITAL_STATUS', 'ETHNICITY', 'GENDER', 'AGE', 'Delirium'],
      dtype='object')

In [62]:
delirium_mimic_dataset.drop(['Unnamed: 0', 'SUBJECT_ID', 'HADM_ID', 'ICUSTAY_ID'], axis=1, inplace=True)

In [63]:
delirium_mimic_dataset

,ABI Ankle BP L,ABI Brachial BP L,ALT,APACHE II,APS,ART BP Systolic,ART BP mean,ART Lumen Volume,AST,Admission Weight (Kg),...,ADMISSION_LOCATION,DISCHARGE_LOCATION,INSURANCE,LANGUAGE,RELIGION,MARITAL_STATUS,ETHNICITY,GENDER,AGE,Delirium
0,NaN,NaN,NaN,NaN,NaN,122.180000,NaN,NaN,NaN,66.739039,...,TRANSFER FROM HOSP/EXTRAM,HOME HEALTH CARE,Medicare,ENGL,CATHOLIC,MARRIED,WHITE,M,75.304110,0
1,NaN,NaN,NaN,NaN,NaN,128.055556,NaN,NaN,NaN,74.382842,...,CLINIC REFERRAL/PREMATURE,HOME HEALTH CARE,Medicare,ENGL,CATHOLIC,MARRIED,WHITE,M,304.805479,0
2,NaN,NaN,12.000000,NaN,NaN,127.950000,NaN,NaN,18.00,106.079589,...,PHYS REFERRAL/NORMAL DELI,LONG TERM CARE HOSPITAL,Medicare,ENGL,NOT SPECIFIED,MARRIED,WHITE,M,72.775342,0
3,NaN,NaN,23.000000,NaN,NaN,111.125000,NaN,NaN,18.00,97.897257,...,CLINIC REFERRAL/PREMATURE,SNF,Medicare,ENGL,CATHOLIC,MARRIED,WHITE,M,76.898630,0
4,NaN,NaN,22.000000,NaN,NaN,104.520000,NaN,NaN,21.00,83.882580,...,CLINIC REFERRAL/PREMATURE,HOME,Medicare,ENGL,CATHOLIC,SEPARATED,HISPANIC OR LATINO,M,70.158904,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8641,NaN,NaN,NaN,NaN,NaN,108.195122,NaN,NaN,NaN,75.920322,...,CLINIC REFERRAL/PREMATURE,REHAB/DISTINCT PART HOSP,Medicare,ENGL,CATHOLIC,MARRIED,WHITE,F,75.698630,0
8642,NaN,NaN,26.500000,NaN,NaN,136.814286,NaN,NaN,24.25,74.517254,...,TRANSFER FROM HOSP/EXTRAM,REHAB/DISTINCT PART HOSP,Medicare,ENGL,CATHOLIC,WIDOWED,WHITE,M,73.852055,0
8643,NaN,NaN,NaN,NaN,NaN,100.800000,NaN,NaN,NaN,73.018827,...,CLINIC REFERRAL/PREMATURE,LEFT AGAINST MEDICAL ADVI,Medicare,ENGL,UNOBTAINABLE,SINGLE,WHITE,F,33.695890,0
8644,NaN,NaN,238.833333,NaN,NaN,105.339943,72.75,NaN,175.00,85.855741,...,CLINIC REFERRAL/PREMATURE,DEAD/EXPIRED,Medicare,ENGL,JEWISH,WIDOWED,WHITE,F,300.200000,0
8645,NaN,NaN,15.333333,NaN,NaN,106.853261,NaN,1.3,16.00,91.432385,...,PHYS REFERRAL/NORMAL DELI,HOME HEALTH CARE,Private,ENGL,CATHOLIC,MARRIED,WHITE,M,68.564384,0

In [64]:
delirium_mimic_dataset.shape

(8646, 96)

In [65]:
missing_vals=delirium_mimic_dataset.isnull().sum()

In [66]:
cols_=list(delirium_mimic_dataset.columns)

In [67]:
missing_vals

ABI Ankle BP L       8642
ABI Brachial BP L    8641
ALT                  4554
APACHE II            8635
APS                  8642
                     ...
MARITAL_STATUS        235
ETHNICITY              37
GENDER                 37
AGE                    37
Delirium                0
Length: 96, dtype: int64

In [68]:
n=0
missing_cols=[]
j=0
for i in missing_vals:
    missingness_percent=100-((8646-i)/8646)*100
    if missingness_percent>30:
        n+=1
        missing_cols.append(cols_[j])
    j+=1
    print(missingness_percent)

99.95373583159842
99.94216978949804
52.67175572519084
99.87277353689568
99.95373583159842
28.9266712930835
92.50520471894518
98.39232014804534
52.77585010409438
29.03076567198704
59.102475133009484
99.95373583159842
99.9884339578996
53.43511450381679
97.74462179042332
1.7349063150589785
99.9884339578996
99.9884339578996
47.02752718019894
70.3793661808929
47.02752718019894
71.559102475133
99.3176035160768
99.3176035160768
1.3647929678464124
95.66273421235253
99.95373583159842
97.88341429562803
99.93060374739764
99.84964145269488
55.55170020818876
65.56789266712931
98.57737682165163
99.86120749479528
99.97686791579922
6.9396252602359425
98.31135785334259
85.264862364099
80.86976636594957
57.11311589174184
57.11311589174184
57.11311589174184
57.11311589174184
57.11311589174184
78.26740689336108
98.2882257691418
99.09784871616932
1.3763590099467962
28.89197316678232
93.5114503816794
85.6349757113116
86.15544760582928
40.064769835762206
98.9590562109646
57.96900300717095
63.30094841545223
94.65648854961832
99.95373583159842
44.73745084432107
80.34929447143188
90.5736756881795
3.9671524404348872
29.64376590330788
31.70252139717789
28.915105250983103
1.156604210039319
93.43048808697664
28.949803377284283
99.91903770529724
1.2491325468424748
29.250520471894518
52.70645385149202
90.29609067777007
90.30765671987047
75.57251908396947
1.839000693962518
92.74809160305344
88.94286375202405
95.68586629655331
83.52995604904002
81.93384223918575
97.12005551700209
92.9909784871617
99.21350913717326
0.4279435577145563
0.4279435577145563
0.4279435577145563
0.4279435577145563
0.4279435577145563
0.8211889891279185
0.4279435577145563
2.7180198935924125
0.4279435577145563
0.4279435577145563
0.4279435577145563
0.0

In [69]:
n

69

In [70]:
len(missing_cols)

69

In [71]:
delirium_mimic_dataset['Delirium'].value_counts()

0    7706
1     940
Name: Delirium, dtype: int64

In [72]:
missing_cols

['ABI Ankle BP L',
 'ABI Brachial BP L',
 'ALT',
 'APACHE II',
 'APS',
 'ART BP mean',
 'ART Lumen Volume',
 'AST',
 'Albumin',
 'AlbuminScore_ApacheIV',
 'Albumin_ApacheIV',
 'Alkaline Phosphate',
 'Ammonia',
 'Aortic Pressure Signal - Diastolic',
 'Aortic Pressure Signal - Systolic',
 'Arterial Base Excess',
 'Arterial Blood Pressure mean',
 'Arterial CO2 Pressure',
 'Arterial O2 Saturation',
 'Assisted Systole',
 'Augmented Diastole',
 'Brain Natiuretic Peptide (BNP)',
 'BunScore_ApacheIV',
 'C Reactive Protein (CRP)',
 'CFI (PiCCO)',
 'CI (PiCCO)',
 'CK (CPK)',
 'CK-MB',
 'CO (Arterial)',
 'CO (PiCCO)',
 'CO2 production',
 'Dialysate Rate',
 'Differential-Atyps',
 'Differential-Bands',
 'Differential-Basos',
 'Differential-Eos',
 'Differential-Lymphs',
 'Differential-Monos',
 'Differential-Neuts',
 'Fibrinogen',
 'Filter Pressure',
 'Gentamicin (Random)',
 'Impaired Skin Depth #1',
 'Impaired Skin Length #1',
 'Impaired Skin Width #1',
 'Inspired O2 Fraction',
 'Intra Cranial Pressure',
 'Ionized Calcium',
 'LDH',
 'LDL measured',
 'LOS pre-ICU admission',
 'Lactic Acid',
 'Lipase',
 'MDI #1 Puff',
 'Non-Invasive Blood Pressure mean',
 'Pulmonary Artery Pressure mean',
 'Skeletal Traction #1 - Pounds',
 'Total Bilirubin',
 'Venous CO2 Pressure',
 'Venous O2 Pressure',
 'Ventilator Tank #1',
 'Chest Tubes Other',
 'Fentanyl',
 'Free Water',
 'Insulin',
 'KCL',
 'Kphos',
 'Protonix',
 'Sodium Phosphate']

In [73]:
delirium_mimic_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8646 entries, 0 to 8645
Data columns (total 96 columns):
ABI Ankle BP L                        4 non-null float64
ABI Brachial BP L                     5 non-null float64
ALT                                   4092 non-null float64
APACHE II                             11 non-null float64
APS                                   4 non-null float64
ART BP Systolic                       6145 non-null float64
ART BP mean                           648 non-null float64
ART Lumen Volume                      139 non-null float64
AST                                   4083 non-null float64
Admission Weight (Kg)                 6136 non-null float64
Albumin                               3536 non-null float64
AlbuminScore_ApacheIV                 4 non-null float64
Albumin_ApacheIV                      1 non-null float64
Alkaline Phosphate                    4026 non-null float64
Ammonia                               195 non-null float64
Anion gap                             8496 non-null float64
Aortic Pressure Signal - Diastolic    1 non-null float64
Aortic Pressure Signal - Systolic     1 non-null float64
Arterial Base Excess                  4580 non-null float64
Arterial Blood Pressure mean          2561 non-null float64
Arterial CO2 Pressure                 4580 non-null float64
Arterial O2 Saturation                2459 non-null float64
Assisted Systole                      59 non-null float64
Augmented Diastole                    59 non-null float64
BUN                                   8528 non-null float64
Brain Natiuretic Peptide (BNP)        375 non-null float64
BunScore_ApacheIV                     4 non-null float64
C Reactive Protein (CRP)              183 non-null float64
CFI (PiCCO)                           6 non-null float64
CI (PiCCO)                            13 non-null float64
CK (CPK)                              3843 non-null float64
CK-MB                                 2977 non-null float64
CO (Arterial)                         123 non-null float64
CO (PiCCO)                            12 non-null float64
CO2 production                        2 non-null float64
Calcium non-ionized                   8046 non-null float64
Dialysate Rate                        146 non-null float64
Differential-Atyps                    1274 non-null float64
Differential-Bands                    1654 non-null float64
Differential-Basos                    3708 non-null float64
Differential-Eos                      3708 non-null float64
Differential-Lymphs                   3708 non-null float64
Differential-Monos                    3708 non-null float64
Differential-Neuts                    3708 non-null float64
Fibrinogen                            1879 non-null float64
Filter Pressure                       148 non-null float64
Gentamicin (Random)                   78 non-null float64
HCO3 (serum)                          8527 non-null float64
Heart Rate                            6148 non-null float64
Impaired Skin Depth #1                561 non-null float64
Impaired Skin Length #1               1242 non-null float64
Impaired Skin Width #1                1197 non-null float64
Inspired O2 Fraction                  5182 non-null float64
Intra Cranial Pressure                90 non-null float64
Ionized Calcium                       3634 non-null float64
LDH                                   3173 non-null float64
LDL measured                          462 non-null float64
LOS pre-ICU admission                 4 non-null float64
Lactic Acid                           4778 non-null float64
Lipase                                1699 non-null float64
MDI #1 Puff                           815 non-null float64
Magnesium                             8303 non-null float64
Non Invasive Blood Pressure mean      6083 non-null float64
Non-Invasive Blood Pressure mean      5905 non-null float64
O2 saturation pulseoxymetry           6146 non-null float64
Potassium (whole blood)               8546 non-null float64
Pulmonary Artery Pressure mean        568 non-null float64
Respiratory Rate                      6143 non-null float64
Skeletal Traction #1 - Pounds         7 non-null float64
Sodium (serum)                        8538 non-null float64
Temperature Celsius                   6117 non-null float64
Total Bilirubin                       4089 non-null float64
Venous CO2 Pressure                   839 non-null float64
Venous O2 Pressure                    838 non-null float64
Ventilator Tank #1                    2112 non-null float64
WBC                                   8487 non-null float64
Chest Tubes Other                     627 non-null float64
Fentanyl                              956 non-null float64
Free Water                            373 non-null float64
Insulin                               1424 non-null float64
KCL                                   1562 non-null float64
Kphos                                 249 non-null float64
Protonix                              606 non-null float64
Sodium Phosphate                      68 non-null float64
LOS                                   8609 non-null float64
ADMISSION_TYPE                        8609 non-null object
ADMISSION_LOCATION                    8609 non-null object
DISCHARGE_LOCATION                    8609 non-null object
INSURANCE                             8609 non-null object
LANGUAGE                              8575 non-null object
RELIGION                              8609 non-null object
MARITAL_STATUS                        8411 non-null object
ETHNICITY                             8609 non-null object
GENDER                                8609 non-null object
AGE                                   8609 non-null float64
Delirium                              8646 non-null int64
dtypes: float64(86), int64(1), object(9)
memory usage: 6.3+ MB

In [74]:
delirium_dataset= delirium_mimic_dataset.drop(missing_cols,axis=1)

In [75]:
delirium_dataset.shape

(8646, 27)

In [76]:
missing_vals_dd=delirium_dataset.isnull().sum()

In [77]:
m=0
for i in missing_vals_dd:
    missingness_percent=(i/8646)*100
    if (100-missingness_percent)>40:
        m+=1
    print(missingness_percent)

28.926671293083505
29.030765671987048
1.7349063150589867
1.364792967846403
6.939625260235947
1.3763590099467962
28.891973166782325
3.9671524404348832
29.64376590330789
28.915105250983114
1.1566042100393246
28.949803377284294
1.2491325468424705
29.25052047189452
1.839000693962526
0.42794355771455006
0.42794355771455006
0.42794355771455006
0.42794355771455006
0.42794355771455006
0.8211889891279205
0.42794355771455006
2.7180198935924125
0.42794355771455006
0.42794355771455006
0.42794355771455006
0.0

In [78]:
delirium_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8646 entries, 0 to 8645
Data columns (total 27 columns):
ART BP Systolic                     6145 non-null float64
Admission Weight (Kg)               6136 non-null float64
Anion gap                           8496 non-null float64
BUN                                 8528 non-null float64
Calcium non-ionized                 8046 non-null float64
HCO3 (serum)                        8527 non-null float64
Heart Rate                          6148 non-null float64
Magnesium                           8303 non-null float64
Non Invasive Blood Pressure mean    6083 non-null float64
O2 saturation pulseoxymetry         6146 non-null float64
Potassium (whole blood)             8546 non-null float64
Respiratory Rate                    6143 non-null float64
Sodium (serum)                      8538 non-null float64
Temperature Celsius                 6117 non-null float64
WBC                                 8487 non-null float64
LOS                                 8609 non-null float64
ADMISSION_TYPE                      8609 non-null object
ADMISSION_LOCATION                  8609 non-null object
DISCHARGE_LOCATION                  8609 non-null object
INSURANCE                           8609 non-null object
LANGUAGE                            8575 non-null object
RELIGION                            8609 non-null object
MARITAL_STATUS                      8411 non-null object
ETHNICITY                           8609 non-null object
GENDER                              8609 non-null object
AGE                                 8609 non-null float64
Delirium                            8646 non-null int64
dtypes: float64(17), int64(1), object(9)
memory usage: 1.8+ MB

In [79]:
correlation = delirium_dataset.corr()

In [80]:
correlation

,ART BP Systolic,Admission Weight (Kg),Anion gap,BUN,Calcium non-ionized,HCO3 (serum),Heart Rate,Magnesium,Non Invasive Blood Pressure mean,O2 saturation pulseoxymetry,Potassium (whole blood),Respiratory Rate,Sodium (serum),Temperature Celsius,WBC,LOS,AGE,Delirium
ART BP Systolic,1.000000,0.007678,0.035667,0.026217,0.015904,0.024312,-0.024958,-0.017484,0.511671,-0.001381,-0.007512,0.001309,0.046345,0.012187,-0.040358,-0.007354,-0.009462,0.021623
Admission Weight (Kg),0.007678,1.000000,-0.028256,0.030475,0.014032,0.150876,-0.003550,0.028492,0.016059,0.018454,0.047744,-0.002284,-0.011312,0.041792,0.001424,0.073527,-0.170617,-0.035339
Anion gap,0.035667,-0.028256,1.000000,0.454481,0.027722,-0.418358,0.031254,0.049901,0.018180,0.000623,0.166851,0.102397,-0.030869,-0.052753,0.099605,-0.031019,0.009247,0.039298
BUN,0.026217,0.030475,0.454481,1.000000,0.023725,-0.143758,-0.057144,0.146985,-0.064613,0.000796,0.219887,0.055553,0.035150,-0.059874,0.045705,0.143858,0.143497,0.034450
Calcium non-ionized,0.015904,0.014032,0.027722,0.023725,1.000000,0.058888,0.029214,0.017251,0.009603,-0.001196,0.016457,0.001490,0.007299,0.031889,-0.008578,0.006853,0.016617,-0.000583
HCO3 (serum),0.024312,0.150876,-0.418358,-0.143758,0.058888,1.000000,-0.038843,0.028038,0.022693,0.010793,-0.056614,0.012549,0.107734,0.024172,-0.111764,0.097789,0.013607,0.030474
Heart Rate,-0.024958,-0.003550,0.031254,-0.057144,0.029214,-0.038843,1.000000,-0.017457,0.055390,-0.003047,-0.013415,0.153052,-0.032210,0.047805,0.065555,0.083746,-0.068791,-0.004243
Magnesium,-0.017484,0.028492,0.049901,0.146985,0.017251,0.028038,-0.017457,1.000000,-0.022309,0.009891,0.131777,0.016382,0.007243,-0.004796,0.033234,0.057481,0.029481,-0.024624
Non Invasive Blood Pressure mean,0.511671,0.016059,0.018180,-0.064613,0.009603,0.022693,0.055390,-0.022309,1.000000,0.001224,-0.013473,-0.004467,0.029495,0.014829,-0.038000,-0.006842,-0.100780,0.027121
O2 saturation pulseoxymetry,-0.001381,0.018454,0.000623,0.000796,-0.001196,0.010793,-0.003047,0.009891,0.001224,1.000000,0.012529,-0.015369,0.001087,0.002834,-0.002274,0.011677,-0.006681,-0.005850
Potassium (whole blood),-0.007512,0.047744,0.166851,0.219887,0.016457,-0.056614,-0.013415,0.131777,-0.013473,0.012529,1.000000,-0.006826,-0.141716,-0.012742,0.039200,-0.042978,0.007497,-0.006966
Respiratory Rate,0.001309,-0.002284,0.102397,0.055553,0.001490,0.012549,0.153052,0.016382,-0.004467,-0.015369,-0.006826,1.000000,0.050481,0.036766,0.092923,0.115576,0.124038,0.002196
Sodium (serum),0.046345,-0.011312,-0.030869,0.035150,0.007299,0.107734,-0.032210,0.007243,0.029495,0.001087,-0.141716,0.050481,1.000000,-0.002376,-0.015102,0.072378,0.073900,0.018394
Temperature Celsius,0.012187,0.041792,-0.052753,-0.059874,0.031889,0.024172,0.047805,-0.004796,0.014829,0.002834,-0.012742,0.036766,-0.002376,1.000000,0.010072,0.075780,-0.078022,0.015950
WBC,-0.040358,0.001424,0.099605,0.045705,-0.008578,-0.111764,0.065555,0.033234,-0.038000,-0.002274,0.039200,0.092923,-0.015102,0.010072,1.000000,0.068740,0.012442,-0.030644
LOS,-0.007354,0.073527,-0.031019,0.143858,0.006853,0.097789,0.083746,0.057481,-0.006842,0.011677,-0.042978,0.115576,0.072378,0.075780,0.068740,1.000000,-0.025494,0.057089
AGE,-0.009462,-0.170617,0.009247,0.143497,0.016617,0.013607,-0.068791,0.029481,-0.100780,-0.006681,0.007497,0.124038,0.073900,-0.078022,0.012442,-0.025494,1.000000,0.026596
Delirium,0.021623,-0.035339,0.039298,0.034450,-0.000583,0.030474,-0.004243,-0.024624,0.027121,-0.005850,-0.006966,0.002196,0.018394,0.015950,-0.030644,0.057089,0.026596,1.000000

In [81]:
delirium_dataset.replace({'GENDER': {'F':1, 'M':0}}, inplace=True)

In [82]:
data = delirium_dataset.values

In [83]:
data

array([[122.18, 66.739039195, 13.5, ..., 0.0, 75.30410958904109, 0],
       [128.05555555555554, 74.38284208225001, 11.5, ..., 0.0,
        304.80547945205484, 0],
       [127.95, 106.079588816, 10.333333333333334, ..., 0.0,
        72.77534246575344, 0],
       ...,
       [100.8, 73.01882654799998, nan, ..., 1.0, 33.6958904109589, 0],
       [105.33994334277621, 85.85574112319999, 18.6, ..., 1.0, 300.2, 0],
       [106.85326086956522, 91.4323854625, 14.826086956521738, ..., 0.0,
        68.56438356164385, 0]], dtype=object)

In [84]:
delirium_dataset.columns

Index(['ART BP Systolic', 'Admission Weight (Kg)', 'Anion gap', 'BUN',
       'Calcium non-ionized', 'HCO3 (serum)', 'Heart Rate', 'Magnesium',
       'Non Invasive Blood Pressure mean', 'O2 saturation pulseoxymetry',
       'Potassium (whole blood)', 'Respiratory Rate', 'Sodium (serum)',
       'Temperature Celsius', 'WBC', 'LOS', 'ADMISSION_TYPE',
       'ADMISSION_LOCATION', 'DISCHARGE_LOCATION', 'INSURANCE', 'LANGUAGE',
       'RELIGION', 'MARITAL_STATUS', 'ETHNICITY', 'GENDER', 'AGE', 'Delirium'],
      dtype='object')

In [85]:
admission_type=delirium_dataset['ADMISSION_TYPE'].tolist()

In [86]:
unique_admission_types=np.unique(admission_type)

In [87]:
unique_admission_types

array(['ELECTIVE', 'EMERGENCY', 'URGENT', 'nan'], dtype='<U9')

In [88]:
ethnicity=delirium_dataset['ETHNICITY'].tolist()

In [89]:
unique_ethnicity=np.unique(ethnicity)

In [90]:
unique_ethnicity

array(['AMERICAN INDIAN/ALASKA NATIVE',
       'AMERICAN INDIAN/ALASKA NATIVE FEDERALLY RECOGNIZED TRIBE',
       'ASIAN', 'ASIAN - ASIAN INDIAN', 'ASIAN - CAMBODIAN',
       'ASIAN - CHINESE', 'ASIAN - FILIPINO', 'ASIAN - JAPANESE',
       'ASIAN - KOREAN', 'ASIAN - OTHER', 'ASIAN - THAI',
       'ASIAN - VIETNAMESE', 'BLACK/AFRICAN', 'BLACK/AFRICAN AMERICAN',
       'BLACK/CAPE VERDEAN', 'BLACK/HAITIAN', 'CARIBBEAN ISLAND',
       'HISPANIC OR LATINO', 'HISPANIC/LATINO - CENTRAL AMERICAN (OTHER)',
       'HISPANIC/LATINO - COLOMBIAN', 'HISPANIC/LATINO - CUBAN',
       'HISPANIC/LATINO - DOMINICAN', 'HISPANIC/LATINO - GUATEMALAN',
       'HISPANIC/LATINO - HONDURAN', 'HISPANIC/LATINO - MEXICAN',
       'HISPANIC/LATINO - PUERTO RICAN', 'HISPANIC/LATINO - SALVADORAN',
       'MIDDLE EASTERN', 'MULTI RACE ETHNICITY',
       'NATIVE HAWAIIAN OR OTHER PACIFIC ISLANDER', 'OTHER',
       'PATIENT DECLINED TO ANSWER', 'PORTUGUESE', 'SOUTH AMERICAN',
       'UNABLE TO OBTAIN', 'UNKNOWN/NOT SPECIFIED', 'WHITE',
       'WHITE - BRAZILIAN', 'WHITE - EASTERN EUROPEAN',
       'WHITE - OTHER EUROPEAN', 'WHITE - RUSSIAN', 'nan'], dtype='<U56')

In [91]:
delirium_dataset.replace({'ETHNICITY': {'HISPANIC/LATINO - COLOMBIAN':'HISPANIC',
                                        'HISPANIC OR LATINO':'HISPANIC',
                                        'HISPANIC/LATINO - CENTRAL AMERICAN (OTHER)':'HISPANIC',
                                        'HISPANIC/LATINO - DOMINICAN':'HISPANIC',
                                        'HISPANIC/LATINO - CUBAN':'HISPANIC',
                                        'HISPANIC/LATINO - GUATEMALAN':'HISPANIC',
                                        'HISPANIC/LATINO - HONDURAN':'HISPANIC',
                                        'HISPANIC/LATINO - MEXICAN':'HISPANIC',
                                        'HISPANIC/LATINO - PUERTO RICAN':'HISPANIC',
                                        'HISPANIC/LATINO - SALVADORAN':'HISPANIC',
                                        'AMERICAN INDIAN/ALASKA NATIVE':'AMERICAN INDIAN',
                                        'AMERICAN INDIAN/ALASKA NATIVE FEDERALLY RECOGNIZED TRIBE':'AMERICAN INDIAN',
                                        'ASIAN - ASIAN INDIAN':'ASIAN', 
                                        'ASIAN - CAMBODIAN':'ASIAN',
                                        'ASIAN - CHINESE':'ASIAN', 
                                        'ASIAN - FILIPINO':'ASIAN', 
                                        'ASIAN - JAPANESE':'ASIAN',
                                        'ASIAN - KOREAN':'ASIAN', 
                                        'ASIAN - OTHER':'ASIAN', 
                                        'ASIAN - THAI':'ASIAN',
                                        'ASIAN - VIETNAMESE':'ASIAN',
                                        'BLACK/AFRICAN':'BLACK', 
                                        'BLACK/AFRICAN AMERICAN':'BLACK',
                                        'BLACK/CAPE VERDEAN':'BLACK', 
                                        'BLACK/HAITIAN':'BLACK',
                                        'WHITE - BRAZILIAN':'WHITE', 'WHITE - EASTERN EUROPEAN':'WHITE',
                                        'WHITE - OTHER EUROPEAN':'WHITE', 'WHITE - RUSSIAN':'WHITE',
                                        'PATIENT DECLINED TO ANSWER':'UNKNOWN/NOT SPECIFIED',
                                        'UNABLE TO OBTAIN':'UNKNOWN/NOT SPECIFIED',
                                       }}, inplace=True)

In [92]:
ethnicity_new=delirium_dataset['ETHNICITY'].tolist()

In [93]:
unique_ethnicity_new=np.unique(ethnicity_new)

In [94]:
unique_ethnicity_new

array(['AMERICAN INDIAN', 'ASIAN', 'BLACK', 'CARIBBEAN ISLAND',
       'HISPANIC', 'MIDDLE EASTERN', 'MULTI RACE ETHNICITY',
       'NATIVE HAWAIIAN OR OTHER PACIFIC ISLANDER', 'OTHER', 'PORTUGUESE',
       'SOUTH AMERICAN', 'UNKNOWN/NOT SPECIFIED', 'WHITE', 'nan'],
      dtype='<U41')

In [ ]:
!pip install datawig

In [95]:
import datawig

In [96]:
delirium_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8646 entries, 0 to 8645
Data columns (total 27 columns):
ART BP Systolic                     6145 non-null float64
Admission Weight (Kg)               6136 non-null float64
Anion gap                           8496 non-null float64
BUN                                 8528 non-null float64
Calcium non-ionized                 8046 non-null float64
HCO3 (serum)                        8527 non-null float64
Heart Rate                          6148 non-null float64
Magnesium                           8303 non-null float64
Non Invasive Blood Pressure mean    6083 non-null float64
O2 saturation pulseoxymetry         6146 non-null float64
Potassium (whole blood)             8546 non-null float64
Respiratory Rate                    6143 non-null float64
Sodium (serum)                      8538 non-null float64
Temperature Celsius                 6117 non-null float64
WBC                                 8487 non-null float64
LOS                                 8609 non-null float64
ADMISSION_TYPE                      8609 non-null object
ADMISSION_LOCATION                  8609 non-null object
DISCHARGE_LOCATION                  8609 non-null object
INSURANCE                           8609 non-null object
LANGUAGE                            8575 non-null object
RELIGION                            8609 non-null object
MARITAL_STATUS                      8411 non-null object
ETHNICITY                           8609 non-null object
GENDER                              8609 non-null float64
AGE                                 8609 non-null float64
Delirium                            8646 non-null int64
dtypes: float64(18), int64(1), object(8)
memory usage: 1.8+ MB

In [97]:
del_train, del_test = datawig.utils.random_split(delirium_dataset)

In [ ]:
#delirium_dataset.drop(['ADMISSION_TYPE','ADMISSION_LOCATION'],axis=1,inplace=True)

In [98]:
missing = delirium_dataset[delirium_dataset['LANGUAGE'].isnull()]

In [99]:
delirium_dataset.columns

Index(['ART BP Systolic', 'Admission Weight (Kg)', 'Anion gap', 'BUN',
       'Calcium non-ionized', 'HCO3 (serum)', 'Heart Rate', 'Magnesium',
       'Non Invasive Blood Pressure mean', 'O2 saturation pulseoxymetry',
       'Potassium (whole blood)', 'Respiratory Rate', 'Sodium (serum)',
       'Temperature Celsius', 'WBC', 'LOS', 'ADMISSION_TYPE',
       'ADMISSION_LOCATION', 'DISCHARGE_LOCATION', 'INSURANCE', 'LANGUAGE',
       'RELIGION', 'MARITAL_STATUS', 'ETHNICITY', 'GENDER', 'AGE', 'Delirium'],
      dtype='object')

In [100]:
cols=['ART BP Systolic', 'Admission Weight (Kg)', 'Anion gap', 'BUN',
       'Calcium non-ionized', 'HCO3 (serum)', 'Heart Rate', 'Magnesium',
       'Non Invasive Blood Pressure mean', 'O2 saturation pulseoxymetry',
       'Potassium (whole blood)', 'Respiratory Rate', 'Sodium (serum)',
       'Temperature Celsius', 'WBC', 'LOS', 'ADMISSION_TYPE',
       'ADMISSION_LOCATION', 'DISCHARGE_LOCATION', 'INSURANCE', 'LANGUAGE',
       'RELIGION', 'MARITAL_STATUS', 'ETHNICITY', 'GENDER', 'AGE', 'Delirium']

In [101]:
cat_vars=['ADMISSION_TYPE',
       'ADMISSION_LOCATION', 'DISCHARGE_LOCATION', 'INSURANCE',
       'RELIGION', 'MARITAL_STATUS', 'ETHNICITY']

In [ ]:
def createImputer(colToImpute):
  data_encoder_cols=[]
  data_featurizer_cols =[]
  if colToImpute in cat_vars:
    label_encoder_cols = [datawig.CategoricalEncoder(colToImpute)]
  else:
    label_encoder_cols = [datawig.NumericalEncoder(colToImpute)]
  for i in cols:
    if i !=colToImpute:
      if i in cat_vars:
        data_encoder_cols.append(datawig.CategoricalEncoder(i))
        data_featurizer_cols.append(datawig.EmbeddingFeaturizer(i))
      else:
        data_encoder_cols.append(datawig.NumericalEncoder(i))
        data_featurizer_cols.append(datawig.NumericalFeaturizer(i))
  imputer = datawig.Imputer(
            data_featurizers = data_featurizer_cols,
            data_encoders = data_encoder_cols,
            label_encoders = label_encoder_cols
)
  return imputer

In [102]:
imputer = datawig.SimpleImputer(
    input_columns=['ART BP Systolic', 'Admission Weight (Kg)', 'Anion gap', 'BUN',
       'Calcium non-ionized', 'HCO3 (serum)', 'Heart Rate', 'Magnesium',
       'Non Invasive Blood Pressure mean', 'O2 saturation pulseoxymetry',
       'Potassium (whole blood)', 'Respiratory Rate', 'Sodium (serum)',
       'Temperature Celsius', 'WBC', 'LOS', 'ADMISSION_TYPE',
       'ADMISSION_LOCATION', 'DISCHARGE_LOCATION', 'INSURANCE',
       'RELIGION', 'MARITAL_STATUS', 'ETHNICITY', 'GENDER', 'AGE', 'Delirium'],
    output_column='LANGUAGE'
    )

In [103]:
imputer.fit(train_df = delirium_dataset)

imputed = imputer.predict(missing)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:3509: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]
/usr/local/lib/python3.7/dist-packages/datawig/calibration.py:92: RuntimeWarning: divide by zero encountered in log
  return np.log(probas)
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [104]:
imputed.columns

Index(['ART BP Systolic', 'Admission Weight (Kg)', 'Anion gap', 'BUN',
       'Calcium non-ionized', 'HCO3 (serum)', 'Heart Rate', 'Magnesium',
       'Non Invasive Blood Pressure mean', 'O2 saturation pulseoxymetry',
       'Potassium (whole blood)', 'Respiratory Rate', 'Sodium (serum)',
       'Temperature Celsius', 'WBC', 'LOS', 'ADMISSION_TYPE',
       'ADMISSION_LOCATION', 'DISCHARGE_LOCATION', 'INSURANCE', 'LANGUAGE',
       'RELIGION', 'MARITAL_STATUS', 'ETHNICITY', 'GENDER', 'AGE', 'Delirium',
       'LANGUAGE_imputed', 'LANGUAGE_imputed_proba'],
      dtype='object')

In [105]:
delirium_dataset.columns

Index(['ART BP Systolic', 'Admission Weight (Kg)', 'Anion gap', 'BUN',
       'Calcium non-ionized', 'HCO3 (serum)', 'Heart Rate', 'Magnesium',
       'Non Invasive Blood Pressure mean', 'O2 saturation pulseoxymetry',
       'Potassium (whole blood)', 'Respiratory Rate', 'Sodium (serum)',
       'Temperature Celsius', 'WBC', 'LOS', 'ADMISSION_TYPE',
       'ADMISSION_LOCATION', 'DISCHARGE_LOCATION', 'INSURANCE', 'LANGUAGE',
       'RELIGION', 'MARITAL_STATUS', 'ETHNICITY', 'GENDER', 'AGE', 'Delirium'],
      dtype='object')

In [106]:
def mergeDFs(df,df_imputed,imputed_col):
  l=imputed_col+'_imputed_proba'
  if l not in list(df_imputed):
    df_imputed2=df_imputed.drop(imputed_col,axis=1)
  else:
    df_imputed2=df_imputed.drop([imputed_col,l],axis=1)
  df=df[df[imputed_col].isnull()==False]
  df_imputed2=df_imputed2.rename(columns = {imputed_col+'_imputed':imputed_col})
  return pd.concat([df,df_imputed2])

In [107]:
delirium_dataset_lang_imp=mergeDFs(delirium_dataset,imputed,'LANGUAGE')

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  if __name__ == '__main__':

In [108]:
delirium_dataset_lang_imp.columns

Index(['ADMISSION_LOCATION', 'ADMISSION_TYPE', 'AGE', 'ART BP Systolic',
       'Admission Weight (Kg)', 'Anion gap', 'BUN', 'Calcium non-ionized',
       'DISCHARGE_LOCATION', 'Delirium', 'ETHNICITY', 'GENDER', 'HCO3 (serum)',
       'Heart Rate', 'INSURANCE', 'LANGUAGE', 'LOS', 'MARITAL_STATUS',
       'Magnesium', 'Non Invasive Blood Pressure mean',
       'O2 saturation pulseoxymetry', 'Potassium (whole blood)', 'RELIGION',
       'Respiratory Rate', 'Sodium (serum)', 'Temperature Celsius', 'WBC'],
      dtype='object')

In [109]:
def imputer(df, col):
  missing = df[df[col].isnull()]
  cols=list(df)
  cols.remove(col)
  #cols.remove('Delirium')
  imputer = datawig.SimpleImputer(
    input_columns=cols,
    output_column=col
    )
  imputer.fit(train_df = df)
  imputed = imputer.predict(missing)
  return mergeDFs(df,imputed,col)

In [110]:
delirium_dataset_disloc_imp=imputer(delirium_dataset_lang_imp,'DISCHARGE_LOCATION')

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:3509: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]
/usr/local/lib/python3.7/dist-packages/datawig/calibration.py:92: RuntimeWarning: divide by zero encountered in log
  return np.log(probas)
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  if __name__ == '__main__':

In [111]:
delirium_dataset_ins_imp=imputer(delirium_dataset_disloc_imp,'INSURANCE')

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:3509: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]
/usr/local/lib/python3.7/dist-packages/datawig/calibration.py:92: RuntimeWarning: divide by zero encountered in log
  return np.log(probas)
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  if __name__ == '__main__':

In [112]:
delirium_dataset_maritalst_imp=imputer(delirium_dataset_ins_imp,'MARITAL_STATUS')

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:3509: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]
/usr/local/lib/python3.7/dist-packages/datawig/calibration.py:92: RuntimeWarning: divide by zero encountered in log
  return np.log(probas)
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  if __name__ == '__main__':

In [113]:
delirium_dataset_eth_imp=imputer(delirium_dataset_maritalst_imp,'ETHNICITY')

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:3509: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]
/usr/local/lib/python3.7/dist-packages/datawig/calibration.py:92: RuntimeWarning: divide by zero encountered in log
  return np.log(probas)
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  if __name__ == '__main__':

In [114]:
delirium_dataset_gend_imp=imputer(delirium_dataset_eth_imp,'GENDER')

/usr/local/lib/python3.7/dist-packages/datawig/calibration.py:92: RuntimeWarning: invalid value encountered in log
  return np.log(probas)
/usr/local/lib/python3.7/dist-packages/datawig/calibration.py:59: RuntimeWarning: invalid value encountered in greater_equal
  bin_mask = (top_probas >= bin_lower) & (top_probas < bin_upper)
/usr/local/lib/python3.7/dist-packages/datawig/calibration.py:59: RuntimeWarning: invalid value encountered in less
  bin_mask = (top_probas >= bin_lower) & (top_probas < bin_upper)
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  if __name__ == '__main__':

In [115]:
delirium_dataset_rel_imp=imputer(delirium_dataset_gend_imp,'RELIGION')

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:3509: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  if __name__ == '__main__':

In [116]:
delirium_dataset_rel_imp.columns

Index(['ADMISSION_LOCATION', 'ADMISSION_TYPE', 'AGE', 'ART BP Systolic',
       'Admission Weight (Kg)', 'Anion gap', 'BUN', 'Calcium non-ionized',
       'DISCHARGE_LOCATION', 'Delirium', 'ETHNICITY', 'GENDER', 'HCO3 (serum)',
       'Heart Rate', 'INSURANCE', 'LANGUAGE', 'LOS', 'MARITAL_STATUS',
       'Magnesium', 'Non Invasive Blood Pressure mean',
       'O2 saturation pulseoxymetry', 'Potassium (whole blood)', 'RELIGION',
       'Respiratory Rate', 'Sodium (serum)', 'Temperature Celsius', 'WBC'],
      dtype='object')

In [117]:
delirium_dataset_admtype_imp=imputer(delirium_dataset_rel_imp,'ADMISSION_TYPE')

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:3509: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  if __name__ == '__main__':

In [119]:
delirium_dataset_admloc_imp=imputer(delirium_dataset_admtype_imp,'ADMISSION_LOCATION')

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:3509: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  if __name__ == '__main__':

In [120]:
delirium_mimic_dataset_missing_imputed=delirium_dataset_admloc_imp

In [121]:
delirium_mimic_dataset_missing_imputed.columns

Index(['ADMISSION_LOCATION', 'ADMISSION_TYPE', 'AGE', 'ART BP Systolic',
       'Admission Weight (Kg)', 'Anion gap', 'BUN', 'Calcium non-ionized',
       'DISCHARGE_LOCATION', 'Delirium', 'ETHNICITY', 'GENDER', 'HCO3 (serum)',
       'Heart Rate', 'INSURANCE', 'LANGUAGE', 'LOS', 'MARITAL_STATUS',
       'Magnesium', 'Non Invasive Blood Pressure mean',
       'O2 saturation pulseoxymetry', 'Potassium (whole blood)', 'RELIGION',
       'Respiratory Rate', 'Sodium (serum)', 'Temperature Celsius', 'WBC'],
      dtype='object')

In [122]:
delirium_mimic_dataset_missing_imputed['RELIGION'].isnull().sum()

0

In [123]:
delirium_mimic_dataset_missing_imputed

,ADMISSION_LOCATION,ADMISSION_TYPE,AGE,ART BP Systolic,Admission Weight (Kg),Anion gap,BUN,Calcium non-ionized,DISCHARGE_LOCATION,Delirium,...,MARITAL_STATUS,Magnesium,Non Invasive Blood Pressure mean,O2 saturation pulseoxymetry,Potassium (whole blood),RELIGION,Respiratory Rate,Sodium (serum),Temperature Celsius,WBC
0,TRANSFER FROM HOSP/EXTRAM,EMERGENCY,75.304110,122.180000,66.739039,13.500000,14.000000,8.150000,HOME HEALTH CARE,0,...,MARRIED,2.050000,67.333333,97.897436,3.650000,CATHOLIC,17.114286,144.000000,36.301587,15.600000
1,CLINIC REFERRAL/PREMATURE,EMERGENCY,304.805479,128.055556,74.382842,11.500000,33.000000,8.550000,HOME HEALTH CARE,0,...,MARRIED,2.350000,68.027778,95.743590,4.250000,CATHOLIC,16.731707,140.500000,36.319444,7.500000
2,PHYS REFERRAL/NORMAL DELI,ELECTIVE,72.775342,127.950000,106.079589,10.333333,21.333333,7.820000,LONG TERM CARE HOSPITAL,0,...,MARRIED,1.933333,77.860000,93.441667,3.850000,NOT SPECIFIED,17.906475,141.500000,37.264444,11.760000
3,CLINIC REFERRAL/PREMATURE,EMERGENCY,76.898630,111.125000,97.897257,14.500000,15.500000,7.250000,SNF,0,...,MARRIED,1.900000,69.010417,96.964912,3.950000,CATHOLIC,28.340426,137.000000,37.156566,8.650000
4,CLINIC REFERRAL/PREMATURE,EMERGENCY,70.158904,104.520000,83.882580,22.000000,103.333333,7.533333,HOME,0,...,SEPARATED,2.466667,51.362745,96.837838,5.066667,CATHOLIC,15.051724,137.666667,36.902778,11.033333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6148,EMERGENCY ROOM ADMIT,EMERGENCY,NaN,130.038462,84.910887,13.000000,14.000000,7.400000,SNF,0,...,MARRIED,1.500000,70.480769,92.866667,4.700000,CATHOLIC,20.423077,132.250000,36.738095,3.425000
6423,EMERGENCY ROOM ADMIT,EMERGENCY,NaN,109.401728,134.274386,11.695652,13.304348,7.981818,SNF,1,...,MARRIED,1.945455,64.184325,95.392308,3.780000,CATHOLIC,17.771084,140.291667,36.879433,11.314286
6943,EMERGENCY ROOM ADMIT,EMERGENCY,NaN,103.044099,79.860214,8.595238,18.674419,7.504255,SNF,0,...,MARRIED,2.064706,57.009804,97.374684,3.998529,CATHOLIC,19.642105,138.895833,37.013135,20.094595
7958,EMERGENCY ROOM ADMIT,EMERGENCY,NaN,124.967442,74.895161,10.812500,25.266667,7.643750,SNF,0,...,MARRIED,2.006250,87.566434,98.310105,3.700000,CATHOLIC,19.019737,143.608696,37.637374,11.888889
8255,EMERGENCY ROOM ADMIT,EMERGENCY,NaN,114.546952,72.817090,13.575758,29.818182,8.542424,SNF,1,...,MARRIED,2.109091,60.255499,97.637097,3.922857,CATHOLIC,21.917160,140.575758,36.734907,13.362069

In [124]:
numr_vars=['ART BP Systolic', 'Admission Weight (Kg)', 'Anion gap', 'BUN',
       'Calcium non-ionized', 'HCO3 (serum)', 'Heart Rate', 'Magnesium',
       'Non Invasive Blood Pressure mean', 'O2 saturation pulseoxymetry',
       'Potassium (whole blood)', 'Respiratory Rate', 'Sodium (serum)',
       'Temperature Celsius', 'WBC', 'LOS', 'AGE']
for var in numr_vars:
  delirium_mimic_dataset_missing_imputed=imputer(delirium_mimic_dataset_missing_imputed,var)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  if __name__ == '__main__':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  if __name__ == '__main__':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  if __name__ == '__main__':
/usr/local/lib/python3.7/dist-packages/datawig/calibration.py:92: RuntimeWarning: invalid value encountered in log
  return np.log(probas)
/usr/local/lib/python3.7/dist-packages/datawig/calibration.py:59: RuntimeWarning: invalid value encountered in greater_equal
  bin_mask = (top_probas >= bin_lower) & (top_probas < bin_upper)
/usr/local/lib/python3.7/dist-packages/datawig/calibration.py:59: RuntimeWarning: invalid value encountered in less
  bin_mask = (top_probas >= bin_lower) & (top_probas < bin_upper)
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  if __name__ == '__main__':
/usr/local/lib/python3.7/dist-packages/datawig/calibration.py:92: RuntimeWarning: invalid value encountered in log
  return np.log(probas)
/usr/local/lib/python3.7/dist-packages/datawig/calibration.py:59: RuntimeWarning: invalid value encountered in greater_equal
  bin_mask = (top_probas >= bin_lower) & (top_probas < bin_upper)
/usr/local/lib/python3.7/dist-packages/datawig/calibration.py:59: RuntimeWarning: invalid value encountered in less
  bin_mask = (top_probas >= bin_lower) & (top_probas < bin_upper)
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  if __name__ == '__main__':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  if __name__ == '__main__':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  if __name__ == '__main__':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  if __name__ == '__main__':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  if __name__ == '__main__':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  if __name__ == '__main__':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  if __name__ == '__main__':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  if __name__ == '__main__':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  if __name__ == '__main__':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  if __name__ == '__main__':
/usr/local/lib/python3.7/dist-packages/datawig/calibration.py:92: RuntimeWarning: invalid value encountered in log
  return np.log(probas)
/usr/local/lib/python3.7/dist-packages/datawig/calibration.py:59: RuntimeWarning: invalid value encountered in greater_equal
  bin_mask = (top_probas >= bin_lower) & (top_probas < bin_upper)
/usr/local/lib/python3.7/dist-packages/datawig/calibration.py:59: RuntimeWarning: invalid value encountered in less
  bin_mask = (top_probas >= bin_lower) & (top_probas < bin_upper)
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  if __name__ == '__main__':
/usr/local/lib/python3.7/dist-packages/datawig/calibration.py:92: RuntimeWarning: invalid value encountered in log
  return np.log(probas)
/usr/local/lib/python3.7/dist-packages/datawig/calibration.py:59: RuntimeWarning: invalid value encountered in greater_equal
  bin_mask = (top_probas >= bin_lower) & (top_probas < bin_upper)
/usr/local/lib/python3.7/dist-packages/datawig/calibration.py:59: RuntimeWarning: invalid value encountered in less
  bin_mask = (top_probas >= bin_lower) & (top_probas < bin_upper)
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  if __name__ == '__main__':

In [125]:
delirium_mimic_dataset_missing_imputed.to_csv("delirium_mimic_dataset_missing_imputed_30.csv")

In [126]:
delirium_mimic_dataset_missing_imputed['Delirium'].value_counts()

0    7706
1     940
Name: Delirium, dtype: int64